import type { ErrorRequestHandler } from "express";

/**
 * Centralised error handler.
 * - Logs the full error server-side (with stack)
 * - Returns a sanitized JSON response without leaking internals
 *
 * Express recognises this as the error-handler middleware because it has 4 args.
 */
export const errorHandler: ErrorRequestHandler = (err, _req, res, _next) => {
  const status =
    (err as { status?: number; statusCode?: number }).status ??
    (err as { statusCode?: number }).statusCode ??
    500;
  const code = (err as { code?: string }).code;

  // Always log full error server-side. Replace with a real logger in Phase E.
  console.error("[error]", {
    status,
    code,
    message: (err as Error).message,
    stack: (err as Error).stack,
  });

  if (status >= 500) {
    res.status(status).json({ error: "Internal error" });
  } else {
    // Client errors: include the message (it was generated by us, no stack)
    res.status(status).json({ error: (err as Error).message });
  }
};

/**
 * Helper for throwing typed HTTP errors from route handlers.
 * Usage: throw httpError(404, 'Project not found');
 */
export function httpError(status: number, message: string): Error {
  const e = new Error(message) as Error & { status: number };
  e.status = status;
  return e;
}
